nav:
  - RankSwift: index.md
  - Server:
    - Server/installation.md
    - Server/setup.md
    - Server/configuration.md
    - Server/commands.md
    - Server/stress-testing.md
    - Server/API.md
  - Roblox: 
    - Roblox/setup.md
    - Roblox/configuration.md
    - Roblox/basic-usage.md
    - Roblox/limiters.md
    - Roblox/Advanced-Usage
    - Example Tutorial:
      - Overview: Roblox/Example-Tutorial/overview.md
      - ServerScript: Roblox/Example-Tutorial/serverscript.md
      - LocalScript: Roblox/Example-Tutorial/localscript.md
    - Roblox/demo.md
  - FAQ: FAQ.md